services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ordermanagement_db'
      - 'POSTGRES_PASSWORD=lmi56n'
      - 'POSTGRES_USER=fmass'
    ports:
      - '5432:5432'
    networks:
      - ordermanagement-network

  api-01: &app
#    container_name: oredermanagement-api-01
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: app1
    environment:
      APP_NAME: ordermanagement
      APP_ENV: dev
    volumes:
      - ./:/app
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '300M'
    networks:
      - ordermanagement-network

#  api-02:
#    <<: *app
#    hostname: app2
#    environment:
#      - SERVER_PORT=8090

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#    network_mode: host
    depends_on:
      - api-01
#      - api-02
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '500M'
    networks:
      - ordermanagement-network

networks:
  ordermanagement-network:
    driver: bridge